export const metadata = {
  title: { default: "Next.js", template: "%s | First App" },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{ backgroundColor: "pink", padding: "10px" }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{ backgroundColor: "pink", margin: "5px", padding: "10px" }}
        >
          <p>Fotter</p>
        </footer>
      </body>
    </html>
  );
}
